### ISSUE TITLE
"Support" navigation entry is linked to an incorrect url

### ISSUE THREAD

**Issue by cipherdragon** [feather-wallet/feather-site#1]
There's a navigation entry called "support" in the site which should be linked to a support page but it is currently point to a "report issue" page, which I think is not the expected behavior. Currently it's pointing to https://docs.featherwallet.org/guides/report-an-issue but I think it should be correctly linked to https://docs.featherwallet.org/guides/donate.

I can work on this issue.

**Comment by jermanuts** [comment]
Pretty sure he meant "Support" as in help. Because the report an issue pages says "support queries", "For live support" etc.

**Comment by tobtoht** [comment]
I've somehow missed this issue and the accompanying PR, sorry for that. The ambiguity of the word 'support' hadn't occurred to me. My intention was indeed to point to the 'report an issue' page.

Would changing "Support" to "Help" be better?

**Comment by jermanuts** [comment]
> Would changing "Support" to "Help" be better?

Agree.

**Comment by tobtoht** [comment]
Done
